version: '3'

services:
  server:
    container_name: server
    build:
      context: ./api
      dockerfile: Dockerfile
    image: server
    command: npm start
    env_file:
      - .env
    ports:
      - $API_LOCAL_PORT:3001
    stdin_open: true
    tty: true
      - front_end

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    image: client
    command: npm run serve
    env_file:
      - .env
    ports:
      - $CLIENT_LOCAL_PORT:5000
    depends_on:
      - server
    stdin_open: true
    tty: true
